name: Test action (Ruby)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-output-method-setup:
    name: min-version=3
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: ruby
          min-version: 3

  test-output-method-load:
    name: min-version=3
    needs: test-output-method-setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-matrix: ${{fromJson(needs.test-output-method-setup.outputs.version-matrix)}}
    steps:
      - name: Setup Ruby ${{ matrix.version-matrix }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version-matrix }}

  test-output-method-setup-eol:
    name: min-version=EOL
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: ruby

  test-output-method-load-eol:
    name: min-version=EOL
    needs: test-output-method-setup-eol
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-matrix: ${{fromJson(needs.test-output-method-setup-eol.outputs.version-matrix)}}
    steps:
      - name: Setup Ruby ${{ matrix.version-matrix }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version-matrix }}

  test-output-method-setup-highest-only:
    name: Highest version only
    runs-on: ubuntu-latest
    outputs:
      highest-version: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: ruby
          highest-only: true

  test-output-method-load-highest-only:
    name: Build for highest version only
    needs: test-output-method-setup-highest-only
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby ${{ needs.test-output-method-setup-highest-only.outputs.highest-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ needs.test-output-method-setup-highest-only.outputs.highest-version }}

  test-output-method-setup-highest-only-strip-patch:
    name: Highest version only (Strip Patch)
    runs-on: ubuntu-latest
    outputs:
      highest-version: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: ruby
          highest-only: true
          remove-patch-version: true

  test-output-method-load-highest-only-strip-patch:
    name: Build for highest version only (Strip Patch)
    needs: test-output-method-setup-highest-only-strip-patch
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby ${{ needs.test-output-method-setup-highest-only-patch-only.outputs.highest-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ needs.test-output-method-setup-highest-only-patch-only.outputs.highest-version }}